name: Manual Release

on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: 'Release type - major, minor or patch'
        required: true
        default: 'patch'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: Setup Node version
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Setup Git
        run: |
          git config --global user.name "devx-sauce-bot"
          git config --global user.email "66365630+devx-sauce-bot@users.noreply.github.com"
      - name: Install dependencies
        run: npm ci
      - name: Release
        run: npm run release:ci -- ${{github.event.inputs.releaseType}}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
